version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: health_notifier_mysql
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: health_notifier
      MYSQL_USER: healthuser
      MYSQL_PASSWORD: healthpassword
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./deployment/init-db.sql:/docker-entrypoint-initdb.d/init-db.sql
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  app:
    build: .
    container_name: health_notifier_app
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=mysql
      - DB_USER=healthuser
      - DB_PASSWORD=healthpassword
      - DB_NAME=health_notifier
      - GEMINI_API_KEY=${GEMINI_API_KEY}
      - WEATHER_API_KEY=${WEATHER_API_KEY}
      - SECRET_KEY=your-secret-key-here
      - FLASK_ENV=production
    depends_on:
      mysql:
        condition: service_healthy
    volumes:
      - .:/app
      - app_logs:/app/logs
    working_dir: /app
    restart: unless-stopped

  nginx:
    image: nginx:alpine
    container_name: health_notifier_nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./deployment/nginx.conf:/etc/nginx/nginx.conf
      - ./deployment/ssl:/etc/nginx/ssl
    depends_on:
      - app
    restart: unless-stopped

volumes:
  mysql_data:
  app_logs:
